mapping = {
    "One": 11,
    "Two": 12,
    "Three": 13,
    "Four": 14,
    "Five": 15,
    "Six": 16,
    "Seven": 17,
    "Eight": 18,
    "Nine": 19,
    "Alphabet A": 20,
    "Alphabet B": 21,
    "Alphabet C": 22,
    "Alphabet D": 23,
    "Alphabet E": 24,
    "Alphabet F": 25,
    "Alphabet G": 26,
    "Alphabet H": 27,
    "Alphabet S": 28,
    "Alphabet T": 29,
    "Alphabet U": 30,
    "Alphabet V": 31,
    "Alphabet W": 32,
    "Alphabet X": 33,
    "Alphabet Y": 34,
    "Alphabet Z": 35,
    "upArrow": 36,
    "downArrow": 37,
    "rightArrow": 38,
    "leftArrow": 39,
    "Stop": 40,
    "Bullseye": -1,
    None: -1
}
